In [ ]:
import pandas as pd
import numpy as np
df = pd.DataFrame({'category': ['A', 'B', 'A', 'C'],'value': [10, 20, 15, 30]})
print(df)
print("\n")
df['category'] = df['category'].astype('category') # Optimized memory usage
print(df.dtypes)

  category  value
0        A     10
1        B     20
2        A     15
3        C     30


category    category
value          int64
dtype: object

In [ ]:
#Vectorized Operations vs. Apply
#Use vectorized operations instead of apply() or loops for better performance.
df['new_value'] = df['value'] * 2 # Vectorized operation

print(df)

#Avoid apply() for row-wise operations unless necessary.
df['new_value'] = df.apply(lambda row: row['value'] * 2, axis=1) # Slower
print(df)

  category  value  new_value
0        A     10         20
1        B     20         40
2        A     15         30
3        C     30         60
  category  value  new_value
0        A     10         20
1        B     20         40
2        A     15         30
3        C     30         60

In [ ]:
#eval() and query() offer faster alternatives to standard pandas operations.
df.eval('new_value = value * 2', inplace=True) # Faster than apply
print(df)

df_filtered = df.query('value > 15') # Efficient filtering
print(df)

  category  value  new_value
0        A     10         20
1        B     20         40
2        A     15         30
3        C     30         60
  category  value  new_value
0        A     10         20
1        B     20         40
2        A     15         30
3        C     30         60

In [ ]:
import pandas as pd

# Define the arrays for MultiIndex
arrays = [
    ['A', 'A', 'B', 'B'],
    [1, 2, 1, 2]
]

# Create a MultiIndex from the arrays with named levels
index = pd.MultiIndex.from_arrays(arrays, names=('Group', 'Num'))

# Create the DataFrame with the MultiIndex
df = pd.DataFrame({'Values': [10, 20, 30, 40]}, index=index)

# Print the DataFrame
print(df)

           Values
Group Num
A     1        10
      2        20
B     1        30
      2        40

In [ ]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Category': ['A', 'A', 'B', 'B'],
    'Type': ['X', 'Y', 'X', 'Y'],
    'Value': [10, 20, 15, 25]
})

# Create a pivot table
pivot_df = df.pivot_table(values='Value', index='Category', columns='Type', aggfunc='sum')

# Print the pivot table
print(pivot_df)

Type       X   Y
Category
A         10  20
B         15  25

In [ ]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Category': ['A', 'A', 'B', 'B'],
    'Type': ['X', 'Y', 'X', 'Y'],
    'Value': [10, 20, 15, 25]
})

# Compute rolling average with a window size of 2
df['rolling_avg'] = df['Value'].rolling(window=2).mean()

# Print the DataFrame with rolling average
print("Rolling Average:")
print(df)

# Compute expanding sum
df['expanding_sum'] = df['Value'].expanding().sum()

# Print the DataFrame with expanding sum
print("\nExpanding Sum:")
print(df)

Rolling Average:
  Category Type  Value  rolling_avg
0        A    X     10          NaN
1        A    Y     20         15.0
2        B    X     15         17.5
3        B    Y     25         20.0

Expanding Sum:
  Category Type  Value  rolling_avg  expanding_sum
0        A    X     10          NaN           10.0
1        A    Y     20         15.0           30.0
2        B    X     15         17.5           45.0
3        B    Y     25         20.0           70.0

In [ ]:
#Use chunksize when reading large files.
chunks = pd.read_csv('/content/car_price_dataset.csv', chunksize=100)
for chunk in chunks:
  print(chunk.head(80))

         Brand   Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  \
0          Kia     Rio  2020          4.2    Diesel          Manual   289944
1    Chevrolet  Malibu  2012          2.0    Hybrid       Automatic     5356
2     Mercedes     GLA  2020          4.2    Diesel       Automatic   231440
3         Audi      Q5  2023          2.0  Electric          Manual   160971
4   Volkswagen    Golf  2003          2.6    Hybrid  Semi-Automatic   286618
..         ...     ...   ...          ...       ...             ...      ...
75       Honda    CR-V  2022          3.4    Diesel       Automatic   248894
76    Mercedes     GLA  2007          2.3  Electric          Manual    76458
77         BMW      X5  2017          3.9    Hybrid  Semi-Automatic     2020
78     Hyundai  Sonata  2018          2.0    Hybrid       Automatic   121567
79  Volkswagen    Golf  2023          3.5    Petrol  Semi-Automatic   139477

    Doors  Owner_Count  Price
0       3            5   8501
1       2            3  12092
2       4            2  11171
3       2            1  11780
4       3            3   2867
..    ...          ...    ...
75      5            2  10622
76      3            5   8970
77      3            2  14059
78      4            4  11568
79      2            5  11710

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
100        Ford  Explorer  2013          5.0  Electric       Automatic
101        Audi        A4  2010          2.0    Hybrid          Manual
102         BMW  5 Series  2001          2.3    Diesel  Semi-Automatic
103      Toyota     Camry  2022          4.5  Electric  Semi-Automatic
104   Chevrolet    Malibu  2005          2.2    Diesel          Manual
..          ...       ...   ...          ...       ...             ...
175  Volkswagen    Passat  2016          3.5    Diesel          Manual
176      Toyota      RAV4  2013          4.3  Electric  Semi-Automatic
177         Kia    Optima  2010          3.8    Petrol       Automatic
178  Volkswagen      Golf  2012          4.2  Electric  Semi-Automatic
179   Chevrolet   Equinox  2009          2.6    Hybrid  Semi-Automatic

     Mileage  Doors  Owner_Count  Price
100   188195      5            3  12736
101   228204      3            4   5535
102    66264      2            1   5374
103   162696      4            2  13946
104   191462      2            4   3970
..       ...    ...          ...    ...
175   271497      5            4   6970
176   225452      4            5   9790
177    51040      5            2  11379
178     7544      2            5  13749
179   264411      3            1   5111

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type Transmission  Mileage  \
200        Audi        A4  2017          2.7  Electric    Automatic   172248
201  Volkswagen      Golf  2017          4.3    Petrol    Automatic   179528
202     Hyundai    Sonata  2014          2.3  Electric       Manual     1752
203    Mercedes       GLA  2008          3.2  Electric       Manual    25557
204         BMW  5 Series  2007          3.9    Hybrid    Automatic   211162
..          ...       ...   ...          ...       ...          ...      ...
275         Kia  Sportage  2010          2.3    Petrol       Manual    62065
276        Audi        Q5  2023          1.9    Diesel       Manual    52679
277      Toyota     Camry  2014          1.0    Petrol       Manual   177766
278       Honda     Civic  2007          1.6  Electric       Manual   158154
279   Chevrolet    Impala  2021          1.3  Electric    Automatic    52051

     Doors  Owner_Count  Price
200      3            2  11955
201      2            5  11409
202      4            2  12564
203      5            4  11188
204      5            5   8376
..     ...          ...    ...
275      2            2   8158
276      5            3  11846
277      3            2   5744
278      3            4   6636
279      5            1  14158

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
300         BMW        X5  2001          4.1  Electric  Semi-Automatic
301    Mercedes   C-Class  2014          2.9    Petrol          Manual
302  Volkswagen    Passat  2010          4.1  Electric       Automatic
303         BMW  5 Series  2016          4.5    Diesel          Manual
304       Honda     Civic  2020          4.4    Petrol  Semi-Automatic
..          ...       ...   ...          ...       ...             ...
375     Hyundai    Tucson  2002          2.6    Petrol  Semi-Automatic
376   Chevrolet    Impala  2019          4.4    Diesel  Semi-Automatic
377  Volkswagen      Golf  2016          4.3    Petrol  Semi-Automatic
378    Mercedes       GLA  2006          3.5  Electric  Semi-Automatic
379   Chevrolet   Equinox  2003          2.0    Hybrid  Semi-Automatic

     Mileage  Doors  Owner_Count  Price
300    87221      5            4   8755
301   217980      4            4   6840
302    71288      5            2  13274
303    91092      2            1  11578
304    24913      3            3  14001
..       ...    ...          ...    ...
375    11401      5            4   7071
376   233465      2            1   9530
377   240885      3            2   8382
378    25049      4            5  10899
379   110430      3            1   5791

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
400  Volkswagen    Passat  2023          3.0    Hybrid       Automatic
401         Kia    Optima  2006          4.6    Hybrid          Manual
402         Kia  Sportage  2002          4.4    Petrol       Automatic
403   Chevrolet    Malibu  2003          1.2    Diesel  Semi-Automatic
404        Ford  Explorer  2019          1.6    Hybrid  Semi-Automatic
..          ...       ...   ...          ...       ...             ...
475        Audi        A4  2020          1.3    Hybrid          Manual
476         BMW  5 Series  2020          2.7    Hybrid  Semi-Automatic
477    Mercedes       GLA  2018          2.0    Hybrid       Automatic
478        Ford     Focus  2009          3.0    Diesel          Manual
479       Honda      CR-V  2020          2.4    Hybrid          Manual

     Mileage  Doors  Owner_Count  Price
400   242006      5            1  11659
401   272450      4            3   6051
402    54982      5            5   9500
403    53980      4            3   5120
404    84291      4            4  10714
..       ...    ...          ...    ...
475   282883      4            1   6742
476   109271      3            4  11614
477   119566      5            5  11608
478    54105      3            2   8717
479   103185      2            3  11436

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
500       Honda      CR-V  2004          1.3  Electric       Automatic
501        Audi        A3  2019          3.1    Diesel  Semi-Automatic
502   Chevrolet    Malibu  2011          4.8  Electric       Automatic
503         Kia       Rio  2006          4.9  Electric          Manual
504         Kia       Rio  2002          3.3    Diesel       Automatic
..          ...       ...   ...          ...       ...             ...
575  Volkswagen    Tiguan  2011          4.2    Hybrid          Manual
576         BMW  5 Series  2009          1.8  Electric  Semi-Automatic
577      Toyota      RAV4  2021          3.3    Diesel       Automatic
578    Mercedes   C-Class  2000          4.2    Petrol          Manual
579    Mercedes   E-Class  2015          2.4    Diesel  Semi-Automatic

     Mileage  Doors  Owner_Count  Price
500   189304      5            1   6313
501   171550      3            5   9469
502    49802      2            4  14703
503    32528      4            3  12149
504   252871      3            2   4442
..       ...    ...          ...    ...
575    49206      5            5  11615
576   115364      2            1   8292
577   291239      5            2   9375
578   270079      5            2   2898
579   260513      4            5   5789

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
600  Volkswagen      Golf  2016          2.8    Hybrid       Automatic
601         BMW  5 Series  2018          3.9  Electric          Manual
602        Ford    Fiesta  2014          2.8  Electric  Semi-Automatic
603     Hyundai   Elantra  2001          4.1    Petrol          Manual
604     Hyundai   Elantra  2005          2.7    Hybrid       Automatic
..          ...       ...   ...          ...       ...             ...
675      Toyota   Corolla  2017          1.6  Electric  Semi-Automatic
676        Ford    Fiesta  2005          4.2    Petrol          Manual
677         BMW  3 Series  2018          5.0    Diesel          Manual
678    Mercedes   E-Class  2014          1.7    Petrol          Manual
679       Honda     Civic  2002          4.3    Diesel          Manual

     Mileage  Doors  Owner_Count  Price
600   218978      2            1   9820
601   216924      5            3  11061
602   136710      5            1  10365
603   187046      2            3   4759
604    45510      2            3   9889
..       ...    ...          ...    ...
675    46400      3            3  11872
676   125377      4            1   7292
677   142084      3            2  11658
678    95579      3            3   8088
679   275483      4            1   3490

[80 rows x 10 columns]
         Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
700      Honda     Civic  2008          4.5    Hybrid       Automatic
701        BMW  5 Series  2023          2.7    Diesel  Semi-Automatic
702       Audi        Q5  2012          3.3    Hybrid  Semi-Automatic
703  Chevrolet   Equinox  2015          2.9    Diesel  Semi-Automatic
704     Toyota   Corolla  2013          1.7  Electric  Semi-Automatic
..         ...       ...   ...          ...       ...             ...
775   Mercedes   C-Class  2021          2.4    Diesel          Manual
776    Hyundai    Sonata  2018          2.3  Electric  Semi-Automatic
777       Audi        Q5  2020          2.5    Diesel       Automatic
778       Ford     Focus  2001          1.2    Petrol  Semi-Automatic
779  Chevrolet   Equinox  2002          2.2    Hybrid          Manual

     Mileage  Doors  Owner_Count  Price
700   140691      3            1  10686
701   151802      5            4  10663
702    47107      2            5  11057
703   116244      2            2   9175
704   248675      3            2   6726
..       ...    ...          ...    ...
775    94705      2            4  10905
776   245073      4            5   8898
777   188803      5            1  10323
778   219120      3            4   2000
779    23277      4            2   7434

[80 rows x 10 columns]
          Brand    Model  Year  Engine_Size Fuel_Type    Transmission  \
800   Chevrolet  Equinox  2002          3.9    Diesel       Automatic
801     Hyundai   Sonata  2000          2.2    Hybrid  Semi-Automatic
802       Honda   Accord  2016          3.1    Hybrid          Manual
803   Chevrolet  Equinox  2020          1.4    Petrol          Manual
804     Hyundai  Elantra  2012          2.2    Diesel  Semi-Automatic
..          ...      ...   ...          ...       ...             ...
875     Hyundai   Tucson  2008          3.5  Electric          Manual
876   Chevrolet  Equinox  2009          1.2  Electric  Semi-Automatic
877        Ford    Focus  2018          4.1  Electric       Automatic
878  Volkswagen     Golf  2009          2.3    Hybrid       Automatic
879         Kia      Rio  2005          4.3    Diesel          Manual

     Mileage  Doors  Owner_Count  Price
800   204351      5            3   6012
801   164580      3            1   4008
802   181002      5            2   9379
803    94143      4            4   9617
804   152845      2            4   6843
..       ...    ...          ...    ...
875    78887      5            2  10422
876   192340      4            4   6153
877   152256      2            5  14054
878    74681      5            5  10106
879   185991      2            1   6180

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
900       Honda     Civic  2009          1.5  Electric          Manual
901         Kia       Rio  2015          1.1    Petrol          Manual
902     Hyundai   Elantra  2016          3.5    Hybrid       Automatic
903  Volkswagen      Golf  2005          4.6    Hybrid  Semi-Automatic
904    Mercedes   C-Class  2023          2.9  Electric       Automatic
..          ...       ...   ...          ...       ...             ...
975        Audi        Q5  2008          3.9    Petrol          Manual
976       Honda     Civic  2004          2.0    Hybrid       Automatic
977         BMW  3 Series  2004          2.2  Electric       Automatic
978     Hyundai    Tucson  2023          2.4    Diesel          Manual
979         Kia       Rio  2020          1.8    Hybrid       Automatic

     Mileage  Doors  Owner_Count  Price
900    87042      2            1   8559
901   191414      5            5   5871
902    22926      2            2  14441
903   215539      2            3   6889
904   102120      4            1  15357
..       ...    ...          ...    ...
975    69232      5            5   9015
976   204272      3            4   5714
977   190504      3            2   7189
978   165233      5            3  10095
979    28207      5            5  13835

[80 rows x 10 columns]
           Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
1000     Hyundai   Elantra  2017          2.4  Electric  Semi-Automatic
1001  Volkswagen      Golf  2005          3.8    Hybrid  Semi-Automatic
1002        Audi        A4  2000          1.6    Diesel          Manual
1003    Mercedes   E-Class  2006          4.5    Diesel          Manual
1004    Mercedes       GLA  2015          2.8  Electric  Semi-Automatic
...          ...       ...   ...          ...       ...             ...
1075        Ford    Fiesta  2017          3.4    Hybrid  Semi-Automatic
1076       Honda    Accord  2002          4.9    Hybrid  Semi-Automatic
1077   Chevrolet    Impala  2011          2.8    Hybrid       Automatic
1078        Audi        A3  2016          2.2    Petrol          Manual
1079         BMW  3 Series  2021          4.7    Hybrid       Automatic

      Mileage  Doors  Owner_Count  Price
1000   269121      5            3   8217
1001   164618      5            1   7107
1002   153107      5            5   2637
1003   117365      3            3   8052
1004    90840      4            4  11583
...       ...    ...          ...    ...
1075   117752      5            1  11244
1076    43827      3            5   9723
1077    30456      2            2  12090
1078    66533      2            2   9769
1079    23265      5            4  17134

[80 rows x 10 columns]
           Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
1100      Toyota   Corolla  2021          4.7  Electric       Automatic
1101    Mercedes   E-Class  2006          1.3    Diesel          Manual
1102   Chevrolet   Equinox  2010          1.2  Electric  Semi-Automatic
1103      Toyota     Camry  2017          3.5    Petrol          Manual
1104         BMW  3 Series  2010          4.2    Petrol          Manual
...          ...       ...   ...          ...       ...             ...
1175   Chevrolet   Equinox  2020          1.5    Diesel          Manual
1176         Kia       Rio  2005          4.1    Petrol  Semi-Automatic
1177  Volkswagen    Tiguan  2004          3.6    Hybrid  Semi-Automatic
1178         Kia       Rio  2020          3.8    Hybrid          Manual
1179      Toyota   Corolla  2011          3.8    Hybrid          Manual

      Mileage  Doors  Owner_Count  Price
1100    14924      5            3  18301
1101    96152      3            4   5276
1102   176673      5            1   6766
1103    89607      2            2  10907
1104    21962      3            4  10860
...       ...    ...          ...    ...
1175   285725      5            4   5885
1176     7131      3            4   9557
1177    29915      4            1   9301
1178   137014      4            3  12159
1179   122932      3            1   9741

[80 rows x 10 columns]
          Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
1200     Toyota   Corolla  2004          1.8  Electric  Semi-Automatic
1201     Toyota     Camry  2021          3.1    Petrol  Semi-Automatic
1202       Ford     Focus  2002          4.6    Diesel          Manual
1203       Ford  Explorer  2004          2.3    Hybrid          Manual
1204  Chevrolet   Equinox  2020          1.9    Petrol       Automatic
...         ...       ...   ...          ...       ...             ...
1275  Chevrolet    Malibu  2017          3.5  Electric       Automatic
1276      Honda     Civic  2012          1.1    Petrol  Semi-Automatic
1277   Mercedes   C-Class  2000          2.6    Hybrid       Automatic
1278       Audi        A4  2006          3.0    Hybrid          Manual
1279       Audi        A3  2008          3.9    Petrol          Manual

      Mileage  Doors  Owner_Count  Price
1200   143927      2            3   6221
1201   216534      4            1   9169
1202   116970      5            5   6960
1203   289970      5            3   2800
1204   157086      3            2  10358
...       ...    ...          ...    ...
1275    59665      3            1  15006
1276   129020      5            2   6219
1277   115173      2            4   6896
1278    16540      2            1   9569
1279    56022      4            4   9279

[80 rows x 10 columns]
           Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
1300     Hyundai    Sonata  2007          4.9    Petrol  Semi-Automatic
1301  Volkswagen    Tiguan  2006          1.1    Petrol  Semi-Automatic
1302         Kia    Optima  2016          2.5    Hybrid       Automatic
1303         BMW  5 Series  2005          4.8  Electric  Semi-Automatic
1304         Kia       Rio  2018          1.2    Petrol  Semi-Automatic
...          ...       ...   ...          ...       ...             ...
1375  Volkswagen    Tiguan  2003          3.4    Diesel          Manual
1376        Ford     Focus  2012          4.6    Hybrid       Automatic
1377      Toyota     Camry  2019          4.8    Petrol          Manual
1378    Mercedes   C-Class  2002          3.6    Hybrid  Semi-Automatic
1379     Hyundai    Sonata  2013          1.2    Petrol       Automatic

      Mileage  Doors  Owner_Count  Price
1300    96380      3            5   9172
1301   149277      5            2   4014
1302   205614      4            3   9787
1303   152453      4            2   9350
1304     4980      5            5  10600
...       ...    ...          ...    ...
1375    19996      3            2   8000
1376   206405      5            5  10671
1377   142494      2            2  11750
1378   173748      4            5   5825
1379   222661      3            4   6246

[80 rows x 10 columns]
           Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
1400  Volkswagen      Golf  2000          2.1    Diesel       Automatic
1401         BMW  5 Series  2019          2.3    Hybrid  Semi-Automatic
1402      Toyota     Camry  2015          4.0    Diesel  Semi-Automatic
1403        Ford     Focus  2001          3.8    Hybrid       Automatic
1404         BMW  3 Series  2000          4.5  Electric  Semi-Automatic
...          ...       ...   ...          ...       ...             ...
1475  Volkswagen    Passat  2018          4.1  Electric  Semi-Automatic
1476         Kia       Rio  2021          3.5    Hybrid          Manual
1477        Ford    Fiesta  2020          2.7    Diesel          Manual
1478         BMW  5 Series  2006          2.4  Electric       Automatic
1479  Volkswagen    Tiguan  2005          1.9    Hybrid       Automatic

      Mileage  Doors  Owner_Count  Price
1400    70286      3            1   6294

In [ ]:
import dask.dataframe as dd
ddf = dd.read_csv('/content/car_price_dataset.csv')
print(ddf.head())

        Brand   Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  \
0         Kia     Rio  2020          4.2    Diesel          Manual   289944
1   Chevrolet  Malibu  2012          2.0    Hybrid       Automatic     5356
2    Mercedes     GLA  2020          4.2    Diesel       Automatic   231440
3        Audi      Q5  2023          2.0  Electric          Manual   160971
4  Volkswagen    Golf  2003          2.6    Hybrid  Semi-Automatic   286618

   Doors  Owner_Count  Price
0      3            5   8501
1      2            3  12092
2      4            2  11171
3      2            1  11780
4      3            3   2867

In [ ]:
df = pd.read_excel("/content/Historicalinvesttemp.xlsx", sheet_name="Sheet1") # Specify sheet name if needed
print(df.head())

  Unnamed: 0                        Unnamed: 1 Unnamed: 2 Unnamed: 3
0        NaN                               NaN        NaN        NaN
1        NaN                               NaN        NaN        NaN
2        NaN                               NaN        NaN        NaN
3        NaN                               NaN        NaN        NaN
4        NaN  Annual Returns on Investments in        NaN        NaN

In [ ]:
df = pd.read_json("iris.json")
print(df.head())

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

In [ ]:
import sqlite3
# Connect to a database
conn = sqlite3.connect("/content/sakila.db")
# Run a SQL query
df = pd.read_sql_query("SELECT * FROM my_table", conn)
print(df.head())

DatabaseError: Execution failed on sql 'SELECT * FROM my_table': no such table: my_table